tiles.setCurrentTilemap(tilemap`level1`)
let player1 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
let player2 = sprites.create(img`
    ........................
    ........................
    ........................
    .......ffff.............
    .....fff22fff...........
    ....fff2222fff..........
    ...fffeeeeeefff.........
    ...ffe222222eef.........
    ...fe2ffffff2ef.........
    ...ffffeeeeffff......ccc
    ..ffefbf44fbfeff....cddc
    ..ffefbf44fbfeff...cddc.
    ..fee4dddddd4eef.ccddc..
    .fdfeeddddd4eeffecddc...
    .fbffee4444ee4fddccc....
    .fbf4f222222f1edde......
    .fcf.f222222f44ee.......
    ..ff.f445544f...........
    .....ffffffff...........
    ......ff..ff............
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
player1.setStayInScreen(true)
player2.setStayInScreen(true)
controller.player1.moveSprite(player1)
controller.player2.moveSprite(player2)
forever(function () {
    player1.vx = randint(-300, 300)
    player1.vy = randint(-300, 300)
    player2.vx = randint(-300, 300)
    player2.vy = randint(-300, 300)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite: Sprite, otherSprite: Sprite) {

})
scene.cameraFollowSprite(player1)
for (let i = 0; i < 100; i++) {
    sprites.create(img`..`, SpriteKind.Projectile)
}